CREATE TABLE "user" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"email" TEXT,
"user_id" TEXT,
"nickname" TEXT,
"is2FA" INTEGER, -- SQLite에서는 BOOLEAN 대신 INTEGER 사용 (0/1)
"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
"modified_at" DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "tournament" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"user_id" INTEGER,
"player_count" INTEGER,
"target_score" INTEGER,
"is_finished" INTEGER, -- BOOLEAN 대신 INTEGER
"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
"modified_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE "game" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"tournament_id" INTEGER,
"player1" TEXT,
"player2" TEXT,
"player1Score" INTEGER,
"player2Score" INTEGER,
"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
"modified_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY ("tournament_id") REFERENCES "tournament"("id")
);
